steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME/style_trainer:latest || exit 0']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--target'
      - 'style_trainer'
      - '-t'
      - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/style_trainer:latest'
      - '--cache-from'
      - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/style_trainer:latest'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/style_trainer:latest'
    id: Push :latest
images:
  - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/style_trainer'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy-cloud-run
