steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/style-trainer:latest || exit 0']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--target'
      - style-trainer
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/style-trainer:latest'
      - '-f'
      - '$_DOCKERFILE'
      - '--cache-from'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/style-trainer:latest'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/style-trainer:latest'
    id: Push :latest
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/style-trainer:latest'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy-cloud-run
