version: "3.8"
services:

  style:
    build:
      context: .
      target: style
      dockerfile: Dockerfile
    image: imagination-ai/style
    entrypoint: python
    volumes:
      - ./style:/applications/style
      - ./common:/applications/common
    ports:
      - "8080:8080"
    networks:
      - backend
#    command: python /application/style/app.py
    restart: "no"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portfolio:
    build:
      context: .
      target: portfolio
      dockerfile: Dockerfile-portfolio
    image: imagination-ai/portfolio
    environment:
      - REACT_APP_STYLE_HOST=style
      - REACT_APP_STYLE_PORT=8080
    ports:
      - "3000:443"
    networks:
      - backend
    restart: "no"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # (TODO: osman) Uncomment when we need it.
  #localstack:
    #image: localstack/localstack:0.11.1
    #networks:
      #- backend
    #ports:
      #- "4566:4566"
      #- "${PORT_WEB_UI:-8080}:${PORT_WEB_UI:-8080}"
    #environment:
      #- SERVICES=sqs,s3
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- DATA_DIR=/tmp/localstack/data
      #- HOSTNAME_EXTERNAL=localstack
      #- AWS_REGION=us-east-1
      #- AWS_DEFAULT_REGION=us-east-1
      #- AWS_SECRET_ACCESS_KEY=AFakeKey
      #- AWS_ACESSS_KEY_ID=AFakeId
      #- DEBUG=${DEBUG- }

networks:
  backend:

volumes:
  db-data: {}
