#### 1. Builder
FROM node:latest as portfolio_build

RUN npm install react-scripts -g --silent

WORKDIR /applications

COPY portfolio/package.json /applications/
COPY portfolio/package-lock.json /applications/

RUN npm ci

ENV PATH /applications/node_modules/.bin:$PATH
COPY portfolio/public /applications/public
COPY portfolio/src /applications/src
COPY portfolio/.env.production .

RUN npm run build

#COPY entrypoints/portfolio-app-entrypoint.sh /applications/portfolio-app-entrypoint.sh
#ENTRYPOINT ["sh", "/applications/portfolio-app-entrypoint.sh"]

#### 2. Leaf
FROM nginx:stable-alpine as portfolio
COPY --from=portfolio_build /applications/build /usr/share/nginx/html
COPY portfolio/nginx/nginx.conf /etc/nginx/conf.d/default.conf

ENV HTTPS true

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
